const fs = require('fs');
const pdfParse = require('pdf-parse');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const Groq = require('groq-sdk');

const extractTextFromPDF = async (filePath) => {
  try {
    const dataBuffer = fs.readFileSync(filePath);
    const data = await pdfParse(dataBuffer);
    return data.text;
  } catch (error) {
    console.error("Error parsing PDF:", error);
    throw new Error("Failed to read PDF file.");
  }
};

const callGeminiAPI = async (text) => {
  const apiKeys = Object.keys(process.env)
    .filter(key => key.startsWith('GEMINI_API_KEY'))
    .map(key => process.env[key])
    .filter(val => val && val.trim() !== '');

  if (apiKeys.length === 0) {
    throw new Error("No Gemini API keys are configured in .env.");
  }

  const prompt = `
You are an expert resume parser. Extract the following information from the provided resume text and return it strictly as a JSON object with no markdown formatting and no extra text.

JSON structure:
{
  "personal_info": {
    "phone": "Extracted phone number, or empty string",
    "location": "Extracted city/country location, or empty string"
  },
  "summary": "A short, autogenerated professional summary based on the resume data.",
  "skills": ["Skill 1", "Skill 2"],
  "languages": ["English", "Spanish"],
  "experience": [
    {
      "companyname": "Company Name",
      "jobtitle": "Job Title",
      "startdate": "YYYY-MM-DD",
      "enddate": "YYYY-MM-DD",
      "description": "Job description",
      "location": "City, Country"
    }
  ],
  "internships": [
    {
      "companyname": "Company Name",
      "jobtitle": "Job Title",
      "startdate": "YYYY-MM-DD",
      "enddate": "YYYY-MM-DD",
      "description": "Internship description",
      "location": "City, Country"
    }
  ],
  "education": [
    {
      "collegename": "University/College Name",
      "degree": "Degree Name",
      "specialisation": "Major/Specialisation",
      "startdate": "YYYY-MM-DD",
      "enddate": "YYYY-MM-DD"
    }
  ]
}

Instructions:
1. "summary": Autogenerate a short, concise profile summary using the resume data.
2. "experience": Extract all work experience items (INCLUDING both full-time jobs AND internships). Combine them all into the "experience" array, sorted chronologically with the most recent first.
3. "internships": Extract all internships and put them in the "internships" array as well sorted in chronologically with the most recent first.
4. "languages": Extract languages if present. If missing, default to ["English"].
5. "skills": Extract key skills.
6. "personal_info": Extract phone number and location (city/country/address).
7. If any section is missing, return an empty array or empty string for it.

Resume Text:
${text}
`;

  const models = [
    "gemini-3.5-flash",
    "gemini-3.1-flash-lite",
    "gemini-1.5-flash"
  ];
  let result = null;
  let lastError = null;

  for (const apiKey of apiKeys) {
    const genAI = new GoogleGenerativeAI(apiKey);
    
    for (const modelName of models) {
      try {
        const model = genAI.getGenerativeModel({ model: modelName });
        result = await model.generateContent(prompt);
        if (result) break;
      } catch (e) {
        lastError = e;
        if (e.status === 403 || e.status === 429) {
          break;
        }
      }
    }
    if (result) break;
  }

  let jsonString = null;
  if (result) {
    jsonString = result.response.text().trim();
  } else if (process.env.GROQ_API_KEY) {
    try {
      const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
      const chatCompletion = await groq.chat.completions.create({
        messages: [{ role: "user", content: prompt }],
        model: "llama-3.3-70b-versatile",
        temperature: 0,
        max_tokens: 2048,
        response_format: { type: "json_object" }
      });
      if (chatCompletion.choices && chatCompletion.choices.length > 0) {
        jsonString = chatCompletion.choices[0].message.content.trim();
        result = true;
      }
    } catch (e) {
      lastError = e;
    }
  }

  if (!result || !jsonString) {
    throw new Error(`All fallback AI models and API keys failed. Last error: ${lastError?.message || 'Unknown'}`);
  }

  if (jsonString.startsWith('\`\`\`json')) {
    jsonString = jsonString.slice(7);
  }
  if (jsonString.startsWith('\`\`\`')) {
    jsonString = jsonString.slice(3);
  }
  if (jsonString.endsWith('\`\`\`')) {
    jsonString = jsonString.slice(0, -3);
  }

  return JSON.parse(jsonString.trim());
};

const parseResumeFile = async (filePath) => {
  const text = await extractTextFromPDF(filePath);
  const parsedData = await callGeminiAPI(text);
  
  if (!parsedData.personal_info?.phone) {
    const phoneMatch = text.match(/(\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}/);
    if (phoneMatch && parsedData.personal_info) {
      parsedData.personal_info.phone = phoneMatch[0].trim();
    }
  }

  return parsedData;
};

module.exports = {
  extractTextFromPDF,
  callGeminiAPI,
  parseResumeFile
};
